# Generated by Django 5.1.4 on 2024-12-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_pharmacy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='MFG_date',
            field=models.DateField(blank=True),
        ),
    ]
