# Generated by Django 5.1.4 on 2024-12-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pmedstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('weight', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expire_date', models.DateField()),
                ('stock', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
                ('details', models.TextField()),
            ],
        ),
    ]
