from django.urls import path
from . import views
from .views import get_unread_count

urlpatterns = [
    path('hello/', views.hello, name='hello'),
    path('signup/', views.signup, name='signup'),
    path('login_view/', views.login_view, name='login_view'),
    path('index/', views.index, name='index'),
    path('pharmacy_list/', views.pharmacy_list, name='pharmacy_list'),
    path('orderdash/', views.orderdash, name='orderdash'),
    path('report/', views.report, name='report'),
    path('pharmacy_list/', views.pharmacy_list, name='pharmacy_list'),
    path('notification/', views.notification, name='notification'),
    path('add_member/', views.add_member, name='add_member'),
    path('mark_notification/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('approve_notification/<int:notification_id>/', views.approve_notification, name='approve_notification'),
    path('delete_notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('view/', views.view, name='view'),
    path('message/', views.message, name='message'),
    #path('view_messages/', views.view_messages, name='view_messages'),
    #path('send_message/', views.send_message, name='send_message'),
    path('pharmacy/<int:pharmacy_id>/detail/', views.pharmacy_detail, name='pharmacy_detail'),
    path('howitwork/', views.howitwork, name='howitwork'),
    path('About_us/', views.About_us, name='About_us'),
    path('contact_us/', views.contact_us, name='contact_us'),
    path('FAQs/', views.FAQs, name='FAQs'),
    path('api/unread_count/', get_unread_count, name='get_unread_count'),
    path('edit/', views.edit_pharmacy_profile, name='edit_pharmacy_profile'),
    path('userdash/', views.current_orders, name='userdash'),
    path('ordering/', views.order_medicine, name='ordering'),
    path('pharorder/', views.current_orders, name='pharorder'),
    path('usernotification/', views.usernotification, name='usernotification'),
    path('usersendmessage/', views.usersendmessage, name='usersendmessage'),
    path('usernotification/', views.message, name='usernotification'),
    path('message_list/', views.message_list, name='message_list'),
    path('message/<int:message_id>/', views.view_message, name='view_message'),
    path('mark_as_read/<int:message_id>/', views.mark_as_read, name='mark_as_read'),
    path('delete_message/<int:message_id>/', views.delete_message, name='delete_message'),
    path('userhome/', views.userhome, name='userhome'),
    path('send/', views.create_notification, name='send'),
    path('reply-message/<int:message_id>/', views.reply_message, name='reply_message'),
    path('userhome/', views.message_view, name='userhome'),
    path('pharmaddmedicine/', views.pharmaddmedicine, name='pharmaddmedicine'),
    path('medicineview/', views.medview, name='medicineview'),
    path('medicinedetails/', views.meddetails, name='medicinedetails'),
    path('resetpass/', views.resetpass, name='resetpass'),
    path('medicineview/', views.medicineview, name='medicineview'),
    path('medicinedetails/', views.medicinedetails, name='medicinedetails'),
    path('incame/', views.incame, name='incame'),
    path('expences/', views.expences, name='expences'),
    path('supplierd/', views.supplierd, name='supplierd'),
    path('medicine_success/', views.medicine_success, name='medicine_success'),
    path('add_medicine/', views.add_medicine, name='add_medicine'),
    path('edit_medicine/<int:M_id>/', views.edit_medicine, name='edit_medicine'),  # Update to use M_ID
    path('delete_medicine/<int:M_id>/', views.delete_medicine, name='delete_medicine'),  # Update to use M_ID
    path('report/', views.sales_report, name='report'),
    path('supplierdashboard/<int:S_id>/', views.dashsupply, name='supplierdashboard'),
    path('supplierdashboard/', views.dashsupply, name='supplierdashboard'),

]
