# Generated by Django 5.1.4 on 2024-12-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_pharmacy_p_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='P_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
