# Generated by Django 5.1.4 on 2024-12-10 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_pharmacy_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='user',
        ),
    ]
