# Generated by Django 5.1.4 on 2024-12-16 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_medicinee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicinee',
        ),
    ]
