# Generated by Django 5.1.4 on 2024-12-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_pmedstock_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, null=True),
        ),
    ]
